import "../styles/globals.css";
import { Quicksand } from "next/font/google";
import Footer from "../components/Footer";
import { ThemeProvider } from "next-themes";
import { ThemeToggle } from "../components/ThemeToggle";
import { NavigationMenu } from "../components/NavigationMenu";

// Font
const Quicksandfont = Quicksand({
  subsets: ["latin"],
  weight: ["600"],
  display: "swap",
  variable: "--font-Quicksand",
});

// Meta datas
export const metadata = {
  title: "Mohan App",
  description: "Portfolio site Generated by create next app",
  icons: {
    icon: "/images/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${Quicksandfont.variable}`}>
      <body className={`antialiased  max-w-xl  mt-8 mx-auto`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NavigationMenu />
          {children}
          <div className="fixed bottom-2 right-5 z-50">
            <ThemeToggle />
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
